### ISSUE TITLE
Te kleine terminal

### ISSUE THREAD

**Issue by elgarvdzande** [LarsBeentjes/GPUScheduling#4]
https://github.com/LarsBeentjes/GPUScheduling/blob/8fe24e8bf43bfd15d22f5f4a2176a4b394b02b28/gpuviewboard/main.py#L35

rob-kean:

Dit gebeurt er als de terminal te klein wordt/is.

Traceback (most recent call last):
  File "./main.py", line 47, in <module>
    main(scr)
  File "./main.py", line 39, in main
    - float(proc['proc_birth']))), proc['gpu_name']))
_curses.error: addwstr() returned ERR

**Comment by elgarvdzande** [comment]
Niet meer relevant want we zijn een andere weg in geslagen
